name: Trigger xenit-home to regenerate docs
on:
  push:
    branches:
      - main

env:
  ENVIRONMENTS: "env1"

jobs:
  call-workflow-1:
    uses: NissesSenap/githubworkflowplay/.github/workflows/workflow.yaml@5a6deba36e364c022afccd08d0b84cd9226dc7b8
    with:
      username: mona
      dir: dir1
      test: true
