name: Trigger xenit-home to regenerate docs
on:
  push:
    branches:
      - main

env:
  ENVIRONMENTS: "env1"

jobs:
  call-workflow-1:
    uses: NissesSenap/githubworkflowplay/.github/workflows/workflow.yaml@8dc62686c449b8cce15f233b01fa5298aef5babe
    with:
      username: mona
      dir: dir1
      test: "true"
