name: Trigger xenit-home to regenerate docs
on:
  push:
    branches:
      - main

env:
  ENVIRONMENTS: "env1"

jobs:
  call-workflow-1:
    uses: NissesSenap/githubworkflowplay/.github/workflows/workflow.yaml@ea984b402debdf26289c2900cdd40aedbfcc31b6
    with:
      username: mona
      dir: dir1
      test: "true"
    secrets:
      DATA: ${{ secrets.DATA }}
