name: Trigger xenit-home to regenerate docs
on:
  push:
    branches:
      - main

jobs:
  call-workflow-1:
    uses: NissesSenap/githubworkflowplay/.github/workflows/workflow.yaml@f073c0668d628bfded6edb5b1ee6738bfd06ab42
    with:
      username: mona
