name: Trigger xenit-home to regenerate docs
on:
  push:
    branches:
      - main

env:
  ENVIRONMENTS: "env1"

jobs:
  call-workflow-1:
    uses: NissesSenap/githubworkflowplay/.github/workflows/workflow.yaml@4a4cefb692107cffc298f2269b6a902c18c0327e
    with:
      username: mona
      dir: dir1
