name: Trigger xenit-home to regenerate docs
on:
  push:
    branches:
      - main

env:
  ENVIRONMENTS: "env1"

jobs:
  call-workflow-1:
    uses: NissesSenap/githubworkflowplay/.github/workflows/workflow.yaml@b23c63198453fbe38c032f16be3204fd2295b462
    with:
      username: mona
      dir: dir1
      test: "true"
    secrets:
      DATA: ${{ secrets.DATA }}
