name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      token:
        default: "something"
        required: false
        type: string

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "username: ${{ inputs.username }}"
          echo "token: ${{ inputs.token }}"
          echo "this is a env: ${ENVIRONMENTS}"
